// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// vmd_1d
Rcpp::List vmd_1d(arma::vec signal, double alpha, double tau, arma::uword K, bool DC, arma::uword init, double tol, bool verbose);
RcppExport SEXP _VMDecomp_vmd_1d(SEXP signalSEXP, SEXP alphaSEXP, SEXP tauSEXP, SEXP KSEXP, SEXP DCSEXP, SEXP initSEXP, SEXP tolSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type signal(signalSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type K(KSEXP);
    Rcpp::traits::input_parameter< bool >::type DC(DCSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type init(initSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(vmd_1d(signal, alpha, tau, K, DC, init, tol, verbose));
    return rcpp_result_gen;
END_RCPP
}
// vmd_2d
Rcpp::List vmd_2d(arma::mat signal, double alpha, double tau, arma::uword K, bool DC, arma::uword init, double tol, bool verbose);
RcppExport SEXP _VMDecomp_vmd_2d(SEXP signalSEXP, SEXP alphaSEXP, SEXP tauSEXP, SEXP KSEXP, SEXP DCSEXP, SEXP initSEXP, SEXP tolSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type signal(signalSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type K(KSEXP);
    Rcpp::traits::input_parameter< bool >::type DC(DCSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type init(initSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(vmd_2d(signal, alpha, tau, K, DC, init, tol, verbose));
    return rcpp_result_gen;
END_RCPP
}
