# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vmd_1d <- function(signal, alpha, tau, K, DC, init, tol, verbose = FALSE) {
    .Call(`_VMDecomp_vmd_1d`, signal, alpha, tau, K, DC, init, tol, verbose)
}

vmd_2d <- function(signal, alpha, tau, K, DC, init, tol, verbose = FALSE) {
    .Call(`_VMDecomp_vmd_2d`, signal, alpha, tau, K, DC, init, tol, verbose)
}

